groups:
  - name: service-name
    services:
      - type: _afpovertcp._tcp
        domain: local
        host: service-name
        ips:
          - "10.0.0.100"
        port: 548
      - type: _device-info._tcp
        domain: local
        host: service-name
        ips:
          - "10.0.0.100"
        port: 1
        txt:
          model: RackMount